version: '3.4'

services:
  nextjs:
    image: stevef2257/jeapordy:latest
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - img-store:/imgs
    environment:
      - MONGO_URL=$MONGO_URL
      - DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - NEXTAUTH_URL_INTERNAL=$NEXTAUTH_URL_INTERNAL

volumes:
  img-store: