version: '3.4'

services:
  nextjs:
    image: stevef2257/jeapordy:latest
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - img-store:/imgs
    environment:
      - MONGO_URL=$MONGO_URL
      - DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - NEXTAUTH_URL_INTERNAL=$NEXTAUTH_URL_INTERNAL
# uncomment to run a mongo container and connect to it using the commented out environment variable
#   db:
#     image: mongo:6.0.4
#     ports:
#       - 27017:27017
#     volumes:
#       - dysh:/data/db

volumes:
  img-store: