export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '../index.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-background font-sans'>
      <body>{children}</body>
    </html>
  )
}
